/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VALERIA BENITEZ
 */
public class guardarPedido extends javax.swing.JFrame {
BaseDatosProducto base = new BaseDatosProducto();

 tienda vis;
 
 String nomb;
 
    /**
     * Creates new form guardarPedido
     */
    public guardarPedido(String nom,tienda paren) {
        initComponents();
        
        
         jCodigo.setVisible(false);
        
        vis = paren;
        nomb = nom;
        try {
            //Connection cn = (Connection) BaseDatos.conexion();
            Connection conn =  BaseDatos.conexion();
            PreparedStatement datos = conn.prepareStatement(
            "select * from Productos where Nombre = '"+nom+"'");
            ResultSet exec = datos.executeQuery();
            if (exec.next()) {
                int id = exec.getInt("codigo");
                jCodigo.setText(String.valueOf(id));
                jNombre.setText(exec.getString("Nombre"));
                //jInventario.setText(String.valueOf(exec.getDouble("Inventario")));
                codProductoB.setText(exec.getString("cod_prod"));
                
            }
            
            
        } catch (Exception e) {
        }

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jInventario = new javax.swing.JTextField();
        jActualizar = new javax.swing.JButton();
        jNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        codProductoB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Inventario: ");

        jActualizar.setText("ACTUALIZAR");
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });

        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("AGREGAR COMPRA DE PRODUCTO");

        jLabel5.setText("Codigo del producto:");

        jCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codProductoB, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jNombre)
                                .addComponent(jInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(57, 57, 57)
                .addComponent(jActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        // TODO add your handling code here:
         if (jNombre.getText().equals("")||jInventario.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Todos los campos son obligatorios");
        }else{

//            String bas = jCodigo.getText();

            int codigo = Integer.parseInt(jCodigo.getText());
            String nombre = jNombre.getText();
            //double Precio = Double.parseDouble(jPrecio.getText());
            double Inventario = Double.parseDouble(jInventario.getText());
            String codProd = codProductoB.getText();
            
            try {
                
                Connection conn = BaseDatos.conexion();
                PreparedStatement datos = conn.prepareStatement(
                        "select * from Productos where Nombre = '" + nomb + "'");
                ResultSet exec = datos.executeQuery();
                if (exec.next()) {
                    int id = exec.getInt("codigo");
                jCodigo.setText(String.valueOf(id));
                jNombre.setText(exec.getString("Nombre"));
               
                jInventario.setText(String.valueOf(exec.getDouble("Inventario")));
                codProductoB.setText(exec.getString("cod_prod"));
               
                    
                    
                    int codigos = exec.getInt("codigo");
                    
                    double precio = exec.getDouble("Precio");
                    double inventa = exec.getDouble("Inventario");
                    String codPrd = exec.getString("cod_prod");
                   
                    double agregar = inventa + Inventario;
                    PreparedStatement datoss;
                     try {
                         
                     String consultaIns = "UPDATE Productos set  Inventario = '"+ agregar+ "'  where codigo = '"+ codigo+"'";
                    
       
            datoss = conn.prepareStatement(consultaIns);
          
            
            
            int filasAfectadas = datoss.executeUpdate();
            if (filasAfectadas > 0) {
                System.out.println("ACTUALIZADO");
            }
           
            
        } catch (SQLException ex) {
            Logger.getLogger(BaseDatosProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
                   // JOptionPane.showMessageDialog(null, "El producto fue borrado");
                }

            } catch (Exception e) {
            }
             
            
           // double porcen = Double.parseDouble(porcentaje.getText());
           // double precioV = Double.parseDouble(precioVenta.getText());

            //Producto nuevito = new Producto(codigo, nombre, Precio, (int) Inventario,codProd,porcen,precioV);
            //vis.base.actualizar(nuevito);
            //vis.rellenar(null);
            JOptionPane.showMessageDialog(null,"Producto actualizado");

            this.dispose();
        }
     
     
     
    
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed

    }//GEN-LAST:event_jNombreActionPerformed

    private void jCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guardarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guardarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guardarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guardarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new guardarPedido().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codProductoB;
    private javax.swing.JButton jActualizar;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JTextField jInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNombre;
    // End of variables declaration//GEN-END:variables
}
