/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5;


// Este proyecto es la continuacion del reto tres pero conectado a una base de datos


import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import static reto3.tienda.toTableMod;

/**
 *
 * @author VALERIA BENITEZ
 */
public class tienda extends javax.swing.JFrame {

//    public void ocultar(Producto nuevo){
//        this.setVisible(false);
//    }
    Reto5 r2 = new Reto5();

    BaseDatosProducto base = new BaseDatosProducto();

    /**
     * Creates new form tienda
     */
    public tienda() {
        initComponents();
        //datosTabla();
        precioVenta.setVisible(false);
        rellenar(null);

    }
    //public static TableModel toTable(BaseDatosProducto base){
    //  HashMap <Integer,Producto> lista = base.listaProductos; 
    //DefaultTableModel model = new DefaultTableModel(new Object[],{1,});

    //}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jActualizar = new javax.swing.JButton();
        jBorrar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jPrecio = new javax.swing.JTextField();
        jInventario = new javax.swing.JTextField();
        jGuardar = new javax.swing.JButton();
        codProductoB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precioVenta = new javax.swing.JTextField();
        porcentaje = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MenosDiez = new javax.swing.JButton();
        ventaBoton = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        palabra = new javax.swing.JTextField();
        Buscar1 = new javax.swing.JButton();
        ventaDia = new javax.swing.JButton();
        informeProd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jActualizar.setText("ACTUALIZAR PRODUCTO");
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });

        jBorrar.setBackground(new java.awt.Color(255, 102, 102));
        jBorrar.setText("BORRAR PRODUCTO");
        jBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("BIENVENIDO A LA APP DE INVENTARIO LAS ACACIAS");

        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel5)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Productos");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Precio: ");

        jLabel4.setText("Inventario: ");

        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });

        jGuardar.setText("GUARDAR");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo producto");

        porcentaje.setText(" ");

        jLabel7.setText("Porcentaje de ganacia:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(porcentaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(jInventario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codProductoB)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(precioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(jGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        MenosDiez.setText("INFORME MIN Y MAX");
        MenosDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosDiezActionPerformed(evt);
            }
        });

        ventaBoton.setText("REALIZAR VENTA");
        ventaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaBotonActionPerformed(evt);
            }
        });

        reset.setText("ACTUALIZAR TABLA");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        Buscar1.setText("BUSCAR");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });

        ventaDia.setText("INFORME VENTAS EN EL DIA");
        ventaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaDiaActionPerformed(evt);
            }
        });

        informeProd.setText("INFORME TOTAL INVENTARIO");
        informeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeProdActionPerformed(evt);
            }
        });

        jButton1.setText("ADICIONAR INVENTARIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ventaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(informeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(MenosDiez)
                        .addGap(60, 60, 60)
                        .addComponent(ventaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ventaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buscar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenosDiez, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ventaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(informeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jNombreActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
        if (jNombre.getText().equals("") || jPrecio.getText().equals("") || jInventario.getText().equals("")) {
            mostrarAd("todos los campos son obligatorios", "Advertencia");
        } else {
            String nombre = jNombre.getText();
            double Precio = Double.parseDouble(jPrecio.getText());
            double Inventario = Double.parseDouble(jInventario.getText());
            String codProd = codProductoB.getText();
            double porcen = Double.parseDouble(porcentaje.getText());
            
            int precioV = 0;
            
            
            
            
            //int cod = base.ultimoCod() + 1;

            base.agregar(new Producto(0, nombre, Precio, (int) Inventario,codProd,porcen,precioV));

            rellenar(null);

            limpiar();

            //JOptionPane.showMessageDialog(this, "El producto fue agregado");
        }

    }//GEN-LAST:event_jGuardarActionPerformed

   
    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        
        int fila = jTable1.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
        } else {
            String nombre = (String) jTable1.getValueAt(fila, 1);

            try {
                Connection conn = BaseDatos.conexion();
                PreparedStatement datos = conn.prepareStatement(
                        "select * from Productos where Nombre = '" + nombre + "'");
                ResultSet exec = datos.executeQuery();
                if (exec.next()) {

                    FrameActualizar frameNuevo = new FrameActualizar(exec.getString("Nombre"), this);

                    frameNuevo.setVisible(true);
                }

            } catch (Exception e) {
            }

//       
        }
    }//GEN-LAST:event_jActualizarActionPerformed

    private void mostrarAd(String str, String title) {
        JOptionPane.showMessageDialog(this, str, title, JOptionPane.WARNING_MESSAGE);
    }


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void jBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarActionPerformed

        int fila = jTable1.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
        } else {
            String Nombre = (String) jTable1.getValueAt(fila, 1);

            try {
                
                Connection conn = BaseDatos.conexion();
                PreparedStatement datos = conn.prepareStatement(
                        "select * from Productos where Nombre = '" + Nombre + "'");
                ResultSet exec = datos.executeQuery();
                if (exec.next()) {
                    int codigo = exec.getInt("codigo");
                    String nom = exec.getString("Nombre");
                    double precio = exec.getDouble("Precio");
                    double inventa = exec.getDouble("Inventario");
                    String codPrd = exec.getString("cod_prod");
                    int porcen = exec.getInt("porcentaje");
                     int precioV = exec.getInt("precio_venta");
                    base.borrar(new Producto(codigo, nom, precio, (int) inventa,codPrd,porcen,precioV));

                    rellenar(null);

                    JOptionPane.showMessageDialog(null, "El producto fue borrado");
                }

            } catch (Exception e) {
            }
            
        }


    }//GEN-LAST:event_jBorrarActionPerformed

    private void MenosDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosDiezActionPerformed
        // TODO add your handling code here:
        TablaInforme info = new TablaInforme();
        info.setVisible(true);
        
        
    }//GEN-LAST:event_MenosDiezActionPerformed

    private void ventaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaBotonActionPerformed
        // TODO add your handling code here:
        compraProductos compra = new compraProductos();
        compra.setVisible(true);
    }//GEN-LAST:event_ventaBotonActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        rellenar(null);
    }//GEN-LAST:event_resetActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
        String nom = null;
        nom = palabra.getText();

        rellenar(nom);

    }//GEN-LAST:event_Buscar1ActionPerformed

    private void ventaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaDiaActionPerformed
        // TODO add your handling code here:
        ventaDia venta = new ventaDia();
        venta.setVisible(true);
        
    }//GEN-LAST:event_ventaDiaActionPerformed

    private void informeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeProdActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        try{
            String ruta = System.getProperty("user.home");
             
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            String fech = dtf.format(LocalDateTime.now());
            PdfWriter.getInstance(documento,new FileOutputStream("C:/Users/toshiba/Documents/ReporteProductos.pdf"));
            documento.open();
            
            PdfPTable table = new PdfPTable(5);
            table.addCell("Codigo");
            table.addCell("Nombre");
            table.addCell("Precio");
            table.addCell("Cantidad");
            table.addCell("Codigo del producto");
            try{
                Connection conn = BaseDatos.conexion();
           
                                    
            
           
            String consulta = "SELECT * FROM Productos";

            Statement result = conn.createStatement();
            ResultSet exec = result.executeQuery(consulta);
                if (exec.next()) {
                    do {
                        table.addCell(exec.getString(1));
                        table.addCell(exec.getString(2));
                        table.addCell(exec.getString(3));
                        table.addCell(exec.getString(4));
                        table.addCell(exec.getString(5));
                    } while (exec.next());
                    documento.add(table);
                    
                }
                
            }catch(DocumentException | SQLException e){
            
        }
            documento.close();
            JOptionPane.showMessageDialog(null, "reporte creado");
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            
        }
        
    }//GEN-LAST:event_informeProdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:int fila = jTable1.getSelectedRow();
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
        } else {
            String nombre = (String) jTable1.getValueAt(fila, 1);

            try {
                Connection conn = BaseDatos.conexion();
                PreparedStatement datos = conn.prepareStatement(
                        "select * from Productos where Nombre = '" + nombre + "'");
                ResultSet exec = datos.executeQuery();
                if (exec.next()) {

                    guardarPedido frameNuevo = new guardarPedido(exec.getString("Nombre"),this);

                    frameNuevo.setVisible(true);
                }

            } catch (Exception e) {
            }

//       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void rellenar(String nom) {
String consulta;
        try {
            
            Connection conn = BaseDatos.conexion();
            if (nom != null ) {
                consulta = "SELECT cod_prod,Nombre,Precio,Inventario,precio_venta FROM Productos where Nombre like ('"+ nom +"%')";
            }else{
           
                consulta = "SELECT cod_prod,Nombre,Precio,Inventario,precio_venta FROM Productos";
                    }
            Statement result = conn.createStatement();
            ResultSet exec = result.executeQuery(consulta);

            DefaultTableModel modelo = new DefaultTableModel();
            jTable1 = new JTable(modelo);
            jScrollPane1.setViewportView(jTable1);

            modelo.addColumn("codigo producto");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio comprado");
            modelo.addColumn("Inventario");
            modelo.addColumn("Precio Venta");
            while (exec.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = exec.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            conn.close();
            

        } catch (SQLException ex) {
          
            JOptionPane.showMessageDialog(null, "Error al llenar la tabla");
        }

    }

    public void limpiar() {
//        this.jNombre.setText("");
//        this.jPrecio.setText("");
//        this.jInventario.setText("");
//        this.codProductoB.setText("");
//        this.porcentaje.setText("");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton MenosDiez;
    private javax.swing.JTextField codProductoB;
    private javax.swing.JButton informeProd;
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jBorrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jGuardar;
    private javax.swing.JTextField jInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField palabra;
    private javax.swing.JTextField porcentaje;
    private javax.swing.JTextField precioVenta;
    private javax.swing.JButton reset;
    private javax.swing.JButton ventaBoton;
    private javax.swing.JButton ventaDia;
    // End of variables declaration//GEN-END:variables

}
