/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto5;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
/**
 *
 * @author VALERIA BENITEZ
 */
public class ventaDia extends javax.swing.JFrame {

    /**
     * Creates new form ventaDia
     */
    public ventaDia() {
        initComponents();
        this.rellenarT();
        vendido();
    }

    public void rellenarT(){
         try {
            Connection conn = BaseDatos.conexion();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
                                    
                                    String fech = dtf.format(LocalDateTime.now());
           
            String consulta = "SELECT * FROM historial_vendidos where fecha like ('"+fech+"%')";

            Statement result = conn.createStatement();
            ResultSet exec = result.executeQuery(consulta);

            DefaultTableModel modelo = new DefaultTableModel();
            jTable1 = new JTable(modelo);
            jScrollPane1.setViewportView(jTable1);

            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre");
            modelo.addColumn("cantidad");
            modelo.addColumn("Precio");
            modelo.addColumn("fecha");

            while (exec.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = exec.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            
            
            
            

        } catch (SQLException ex) {
          
            JOptionPane.showMessageDialog(null, "Error al llenar la tabla");
        }
    }
    
    public void vendido(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        List<Integer> ab = new ArrayList<>();


       Object model1 = null;
       Object model2 = null;

        for(int i = 0; i < modelo.getRowCount();i++){
            model1 = modelo.getValueAt(i,2);
            model2 =  modelo.getValueAt(i,3);
            System.out.println(model1);
            
            System.out.println(model2);
            double num1 = Double.valueOf((double)model1);
            System.out.println(num1);
            double num2 = Double.valueOf((double) model2);
            int numero2 = (int) num2;
            int numero1 = (int) num1;
            int ac = (int) numero1 * numero2;
            
            ab.add(ac);
        }
        System.out.println(ab);
        int suma = 0;
        for (int x = 0; x < ab.size(); x++) {
            suma = suma + ab.get(x);
            
         }
        String sum = String.valueOf(suma);
        totalVentas.setText((String)sum);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalVentas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        generar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        totalVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Total Vendido");

        generar.setText("GENERAR INFORME");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ventas del dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(volver)
                            .addGap(49, 49, 49)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(totalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(totalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        try{
            String ruta = System.getProperty("user.home");
             
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            String fech = dtf.format(LocalDateTime.now());
            PdfWriter.getInstance(documento,new FileOutputStream("C:/Users/toshiba/Documents/ReporteVentasDia.pdf"));
            documento.open();
            
            PdfPTable table = new PdfPTable(5);
            table.addCell("Codigo");
            table.addCell("Nombre");
            table.addCell("Cantidad");
            table.addCell("precio");
            table.addCell("fecha");
            try{
                Connection conn = BaseDatos.conexion();
           
                                    
            
           
            String consulta = "SELECT * FROM historial_vendidos ";

            Statement result = conn.createStatement();
            ResultSet exec = result.executeQuery(consulta);
                if (exec.next()) {
                    do {
                        table.addCell(exec.getString(1));
                        table.addCell(exec.getString(2));
                        table.addCell(exec.getString(3));
                        table.addCell(exec.getString(4));
                        table.addCell(exec.getString(5));
                    } while (exec.next());
                    documento.add(table);
                    
                }
                
            }catch(DocumentException | SQLException e){
            
        }
            documento.close();
            JOptionPane.showMessageDialog(null, "reporte creado");
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            
        }
        
    }//GEN-LAST:event_generarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
     
        this.dispose();
        
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventaDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventaDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventaDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventaDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventaDia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField totalVentas;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
